In [1]:
import numpy as np

a = np.array([2, 3, 4], dtype=np.uint32)

b = np.array([5, 6, 7], dtype=np.uint32)

c = a - b

print('unsigned c:', c, c.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


1D Array Making

In [2]:
a = np.arange(10,40,5,dtype=int)
print(a)

b = np.linspace(4,8,5,dtype=int)

print(b)

[10 15 20 25 30 35]
[4 5 6 7 8]


In [3]:
a = np.zeros(5,dtype=int)
print(a)

b = np.ones(6)
print(b.astype(np.int64))

c = np.empty(3,dtype=int)
print(c)

[0 0 0 0 0]
[1 1 1 1 1 1]
[5 6 7]


In [4]:
import numpy as np
CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    print(average)
    print(change)
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)

print(curve(grades))

60.75
19.25
[ 91.25  54.25  83.25 100.    70.25 100.    93.25  31.25]


In [5]:
a = np.array([[1,2,3], [4,5,6]])

b = a.reshape(6)
print(b)

[1 2 3 4 5 6]


In [ ]:
x = np.array([[1, 2], [3, 4]])

y = np.array([[5,6,0],[8,7,9]])

a = np.concatenate((x,y),axis=1)
print(a)

[[1 2 5 6 0]
 [3 4 8 7 9]]


In [19]:
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10]
print(my_list[::2])

[0, 2, 4, 6, 8, 10]


###  Dürer’s magic square!

In [ ]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34

    