In [7]:
import numpy as np

a = np.array([2, 3, 4], dtype=np.uint32)

b = np.array([5, 6, 7], dtype=np.uint32)

c = a - b

print('unsigned c:', c, c.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


1D Array Making

In [16]:
a = np.arange(10,40,5,dtype=int)
print(a)

b = np.linspace(4,8,5,dtype=int)

print(b)

[10 15 20 25 30 35]
[4 5 6 7 8]


In [29]:
a = np.zeros(5,dtype=int)
print(a)

b = np.ones(6)
print(b.astype(np.int64))

c = np.empty(3,dtype=int)
print(c)

[0 0 0 0 0]
[1 1 1 1 1 1]
[16843009 16843009 16843009]


2d Matrix making